# Generated by Django 3.2.25 on 2024-06-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topay',
            name='county',
        ),
        migrations.RemoveField(
            model_name='topay',
            name='town_or_city',
        ),
        migrations.AlterField(
            model_name='topay',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='topay',
            name='states',
            field=models.CharField(choices=[('London', 'London'), ('Bradford', 'Bradford'), ('Wakefield', 'Wakefield'), ('Nottingham', 'Nottingham'), ('Westminster', 'Westminster'), ('Coventry', 'Coventry'), ('Birmingham', 'Birmingham'), ('Liverpool', 'Liverpool'), ('Leeds', 'Leeds'), ('Bristol', 'Bristol'), ('Manchester', 'Manchester'), ('Leicester', 'Leicester')], max_length=40),
        ),
    ]
