# Generated by Django 3.2.25 on 2024-07-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order_total',
        ),
    ]
