# Generated by Django 3.2.25 on 2024-06-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
        ('checkout', '0002_auto_20240627_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItem',
            new_name='ToPayLineItem',
        ),
        migrations.RenameField(
            model_name='topay',
            old_name='states',
            new_name='state',
        ),
    ]
