# Generated by Django 3.2.25 on 2024-07-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_checkout_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
