# Generated by Django 3.2.25 on 2024-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20240628_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='topay',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='topay',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='topay',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
