# Generated by Django 3.2.25 on 2024-07-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkout_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.CharField(choices=[(None, 'City'), ('London', 'London'), ('Bradford', 'Bradford'), ('Wakefield', 'Wakefield'), ('Nottingham', 'Nottingham'), ('Westminster', 'Westminster'), ('Coventry', 'Coventry'), ('Birmingham', 'Birmingham'), ('Liverpool', 'Liverpool'), ('Leeds', 'Leeds'), ('Bristol', 'Bristol'), ('Manchester', 'Manchester'), ('Leicester', 'Leicester')], max_length=40),
        ),
    ]
